name: ud05-ia-stack

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_MODEL=llama3.2:3b
    depends_on:
      ollama:
        condition: service_started
    networks:
      - ia-net

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_storage:/root/.ollama
    networks:
      - ia-net

networks:
  ia-net:
    driver: bridge

volumes:
  ollama_storage:
